---
- name: Gather Info
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve snapshot information for a VM
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        vm_type: vm
      delegate_to: localhost
      register: template_info

    - debug:
        var: vm_info.virtual_machines
