---
- name: Provision VM on VMware vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clone VM from template
      community.vmware.vm_vm_vm_drs_rule:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster: "{{ cluster_name }}"
        validate_certs: no
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        datastore: "{{ datastore_name }}"
        network: "{{ network_name }}"
        state: powered_on
        hardware:
          num_cpus: "{{ vm_cpu }}"
          memory_mb: "{{ vm_memory }}"
          disk:
            size_gb: "{{ vm_disk_size }}"
        wait_for_ip_address: yes
      delegate_to: localhost
