---
- name: Create a VM in vCenter
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Create VM in vCenter"
      vmware_guest:
        hostname: "{{ lookup('env', 'VCENTER_HOSTNAME')}}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"    
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder_name }}"
        name: "{{ vm_name }}"
        template: "{{ template_name }}"          # Template to clone from
        cluster: "{{ cluster_name }}"
        datastore: "{{ datastore_name }}"
        state: poweredon                         # Options: present, absent, poweredon, poweredoff
        hardware:
          memory_mb: 2048                        # Memory in MB
          num_cpus: 2                            # Number of vCPUs
          scsi: paravirtual
        networks:
          - name: "{{ network_name }}"
            ip: "{{ ip_address }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            type: static                         # Options: dhcp, static
        disk:
          - size_gb: 20                          # Disk size in GB
            type: thin                           # Disk type: thin, thick, eagerzeroed
            datastore: "{{ datastore_name }}"
        customvalues:
          - key: notes                           # Adding custom attributes
            value: "Provisioned by Ansible"
      register: deploy_vm_result

    - name: "Display VM creation result"
      debug:
        var: deploy_vm_result
        